# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fo_business_process_name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='LineOfBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fo_line_of_business_name', models.CharField(max_length=100, verbose_name='Отрасль производства')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessProcessAdmin',
            fields=[
                ('businessprocess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FoBusinessProcess.BusinessProcess')),
            ],
            bases=('FoBusinessProcess.businessprocess',),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='fo_line_of_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='FoBusinessProcess.LineOfBusiness', verbose_name='Отрасль производства'),
        ),
    ]
