# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoBusinessProcess', '0002_auto_20170425_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprocess',
            name='fo_business_process_manager',
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='fo_line_of_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='FoBusinessProcess.LineOfBusiness', verbose_name='Отрасль производства(линия бизнеса)'),
        ),
    ]
