# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0014_workinggrouppartner_fo_right_invite_group'),
        ('FoBusinessProcess', '0003_auto_20170426_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocess',
            name='fo_business_process_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.ProtectedError, to='FOadmin.CompanyStructure', verbose_name='Руководитель Бизнесс процесса'),
            preserve_default=False,
        ),
    ]
