# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0014_workinggrouppartner_fo_right_invite_group'),
        ('FoBusinessProcess', '0004_businessprocess_fo_business_process_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocess',
            name='fo_client_person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.ProtectedError, to='FOadmin.Profile', verbose_name='Заказчик физическое лицо'),
            preserve_default=False,
        ),
    ]
