# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoBusinessProcess', '0005_businessprocess_fo_client_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprocess',
            name='fo_client_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.ProtectedError, to='FOadmin.Profile', verbose_name='Заказчик физическое лицо'),
        ),
    ]
