# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoCounterparty', '0001_initial'),
        ('FoBusinessProcess', '0006_auto_20170426_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocess',
            name='fo_client_legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.ProtectedError, to='FoCounterparty.LegalEntity', verbose_name='Заказчик Юридическое лицо'),
        ),
    ]
