# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoBusinessProcess', '0007_businessprocess_fo_client_legal_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprocess',
            name='fo_client_legal_entity',
        ),
        migrations.RemoveField(
            model_name='businessprocess',
            name='fo_client_person',
        ),
    ]
