# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 06:41
from __future__ import unicode_literals

import FOadmin.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'Структура компании',
                'verbose_name_plural': 'Структура компании',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fo_user_last_name', models.CharField(default='-', max_length=50, verbose_name='Фамилия')),
                ('fo_user_name', models.CharField(default='-', max_length=50, verbose_name='Имя')),
                ('fo_user_patronymic', models.CharField(default='-', max_length=50, verbose_name='Отчество')),
                ('fo_user_birthday', models.DateField(default='1900-01-01', verbose_name='День рождения')),
                ('fo_user_email', models.EmailField(default='test@test.ru', max_length=254, verbose_name='Email')),
                ('fo_user_type_phone_1', models.CharField(choices=[('WP', 'Рабочий телефон'), ('PP', 'Личный телефон'), ('CP', 'Сотовый телефон'), ('IP', 'Внутренний телефон')], default='WP', max_length=2, verbose_name='Тип телефона')),
                ('fo_user_phone_1', models.CharField(default='-', max_length=20, verbose_name='№ телефона')),
                ('fo_user_type_phone_2', models.CharField(choices=[('WP', 'Рабочий телефон'), ('PP', 'Личный телефон'), ('CP', 'Сотовый телефон'), ('IP', 'Внутренний телефон')], default='WP', max_length=2, verbose_name='Тип телефона')),
                ('fo_user_phone_2', models.CharField(default='-', max_length=20, verbose_name='№ телефона')),
                ('fo_user_type_phone_3', models.CharField(choices=[('WP', 'Рабочий телефон'), ('PP', 'Личный телефон'), ('CP', 'Сотовый телефон'), ('IP', 'Внутренний телефон')], default='WP', max_length=2, verbose_name='Тип телефона')),
                ('fo_user_phone_3', models.CharField(default='-', max_length=20, verbose_name='№ телефона')),
                ('fo_user_type_phone_4', models.CharField(choices=[('WP', 'Рабочий телефон'), ('PP', 'Личный телефон'), ('CP', 'Сотовый телефон'), ('IP', 'Внутренний телефон')], default='WP', max_length=2, verbose_name='Тип телефона')),
                ('fo_user_phone_4', models.CharField(default='-', max_length=20, verbose_name='№ телефона')),
                ('fo_user_photo', models.ImageField(blank=True, upload_to=FOadmin.models.fo_user_upload_path, verbose_name='Фото пользователя')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'ordering': ['fo_user_last_name'],
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='ReferenceBookPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fo_position_name', models.CharField(max_length=100, unique=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Справочник должностей',
            },
        ),
        migrations.CreateModel(
            name='TestMptt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
            ],
        ),
        migrations.AddField(
            model_name='companystructure',
            name='fo_book_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.ProtectedError, to='FOadmin.ReferenceBookPosition', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='companystructure',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='FOadmin.CompanyStructure', verbose_name='Кому подчиняется'),
        ),
    ]
