# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fo_department_name', models.CharField(max_length=100, unique=True, verbose_name='Отдел')),
            ],
        ),
        migrations.DeleteModel(
            name='TestMptt',
        ),
    ]
