# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0002_companystructure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companystructure',
            options={'verbose_name': 'Структура компании', 'verbose_name_plural': 'Структура компании'},
        ),
        migrations.AlterField(
            model_name='companystructure',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
