# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0002_auto_20170404_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Справочник отделов'},
        ),
        migrations.AddField(
            model_name='companystructure',
            name='fo_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.ProtectedError, to='FOadmin.Department', verbose_name='Должность'),
        ),
    ]
