# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0003_auto_20170222_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystructure',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
