# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0003_auto_20170213_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fo_user_birthday',
            field=models.DateField(default='2017-01-02', verbose_name='День рождения'),
            preserve_default=False,
        ),
    ]
