# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0004_auto_20170406_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystructure',
            name='fo_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.ProtectedError, to='FOadmin.Profile', verbose_name='ФИО'),
        ),
    ]
