# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0004_companystructure_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceBookPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fo_position_name', models.CharField(max_length=100, unique=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name_plural': 'Справочник должностей',
                'verbose_name': 'Должность',
            },
        ),
    ]
