# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0005_auto_20170213_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fo_user_birthday',
            field=models.DateField(default='1900-01-01', verbose_name='День рождения'),
        ),
    ]
