# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0005_companystructure_fo_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fo_working_group_name', models.CharField(max_length=100, unique=True, verbose_name='Рабочая группа')),
                ('fo_auto_now_add', models.DateField(auto_now_add=True, verbose_name='Дата создания группы')),
                ('fo_working_group_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.ProtectedError, to='FOadmin.Profile', verbose_name='Кто создал ФИО')),
            ],
        ),
    ]
