# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 06:20
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0005_referencebookposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companystructure',
            name='order',
        ),
        migrations.AlterField(
            model_name='companystructure',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='FOadmin.CompanyStructure', verbose_name='Кому подчиняется'),
        ),
    ]
