# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0006_workinggroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinggroup',
            options={'verbose_name': 'Рабочая группа', 'verbose_name_plural': 'Рабочии группы'},
        ),
        migrations.AlterField(
            model_name='workinggroup',
            name='fo_working_group_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.ProtectedError, to='FOadmin.Profile', verbose_name='Кто создал ФИО'),
            preserve_default=False,
        ),
    ]
