# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0006_auto_20170310_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencebookposition',
            name='fo_company_structure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.ProtectedError, related_name='fo_position', to='FOadmin.CompanyStructure'),
            preserve_default=False,
        ),
    ]
