# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0007_auto_20170213_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['fo_user_last_name'], 'verbose_name': 'Информацию о пользователе', 'verbose_name_plural': 'Информация о пользователях'},
        ),
    ]
