# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0007_auto_20170406_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingGroupPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fo_working_group_partner_profile', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='FOadmin.Profile', verbose_name='Участники группы ФИО')),
            ],
        ),
    ]
