# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0007_referencebookposition_fo_company_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencebookposition',
            name='fo_company_structure',
        ),
    ]
