# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0008_remove_referencebookposition_fo_company_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystructure',
            name='fo_book_position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.ProtectedError, to='FOadmin.ReferenceBookPosition'),
            preserve_default=False,
        ),
    ]
