# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0008_auto_20170213_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fo_user_email',
            field=models.EmailField(default='test@test.ru', max_length=254, verbose_name='Email'),
        ),
    ]
