# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0008_workinggrouppartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinggrouppartner',
            name='fo_working_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.ProtectedError, to='FOadmin.WorkingGroup', verbose_name='Рабочая группа'),
            preserve_default=False,
        ),
    ]
