# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0009_profile_fo_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fo_user_phone_1',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='fo_user_phone_2',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='fo_user_phone_3',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='fo_user_phone_4',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='fo_user_type_phone_1',
            field=models.CharField(choices=[('WP', 'Рабочий телефон'), ('PP', 'Личный телефон'), ('CP', 'Сотовый телефон'), ('IP', 'Внутренний телефон')], default='WP', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='fo_user_type_phone_2',
            field=models.CharField(choices=[('WP', 'Рабочий телефон'), ('PP', 'Личный телефон'), ('CP', 'Сотовый телефон'), ('IP', 'Внутренний телефон')], default='WP', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='fo_user_type_phone_3',
            field=models.CharField(choices=[('WP', 'Рабочий телефон'), ('PP', 'Личный телефон'), ('CP', 'Сотовый телефон'), ('IP', 'Внутренний телефон')], default='WP', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='fo_user_type_phone_4',
            field=models.CharField(choices=[('WP', 'Рабочий телефон'), ('PP', 'Личный телефон'), ('CP', 'Сотовый телефон'), ('IP', 'Внутренний телефон')], default='WP', max_length=2),
        ),
    ]
