# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 10:30
from __future__ import unicode_literals

import FOadmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0010_auto_20170215_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['fo_user_last_name'], 'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AddField(
            model_name='profile',
            name='fo_user_photo',
            field=models.ImageField(blank=True, upload_to=FOadmin.models.fo_user_upload_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fo_user_phone_1',
            field=models.CharField(default='-', max_length=20, verbose_name='№ телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fo_user_phone_2',
            field=models.CharField(default='-', max_length=20, verbose_name='№ телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fo_user_phone_3',
            field=models.CharField(default='-', max_length=20, verbose_name='№ телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fo_user_phone_4',
            field=models.CharField(default='-', max_length=20, verbose_name='№ телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fo_user_type_phone_1',
            field=models.CharField(choices=[('WP', 'Рабочий телефон'), ('PP', 'Личный телефон'), ('CP', 'Сотовый телефон'), ('IP', 'Внутренний телефон')], default='WP', max_length=2, verbose_name='Тип телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fo_user_type_phone_2',
            field=models.CharField(choices=[('WP', 'Рабочий телефон'), ('PP', 'Личный телефон'), ('CP', 'Сотовый телефон'), ('IP', 'Внутренний телефон')], default='WP', max_length=2, verbose_name='Тип телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fo_user_type_phone_3',
            field=models.CharField(choices=[('WP', 'Рабочий телефон'), ('PP', 'Личный телефон'), ('CP', 'Сотовый телефон'), ('IP', 'Внутренний телефон')], default='WP', max_length=2, verbose_name='Тип телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fo_user_type_phone_4',
            field=models.CharField(choices=[('WP', 'Рабочий телефон'), ('PP', 'Личный телефон'), ('CP', 'Сотовый телефон'), ('IP', 'Внутренний телефон')], default='WP', max_length=2, verbose_name='Тип телефона'),
        ),
    ]
