# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0011_auto_20170407_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinggrouppartner',
            options={'verbose_name': 'Участник рабочей группы', 'verbose_name_plural': 'Участники рабочей группы'},
        ),
    ]
