# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0011_auto_20170215_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fo_user_photo',
            field=models.ImageField(blank=True, upload_to='/media/fo_user'),
        ),
    ]
