# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0012_auto_20170215_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fo_user_photo',
        ),
    ]
