# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0012_auto_20170411_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinggrouppartner',
            name='fo_working_group_admin',
            field=models.BooleanField(default=False, verbose_name='Администратор группы'),
        ),
    ]
