# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOadmin', '0013_workinggrouppartner_fo_working_group_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinggrouppartner',
            name='fo_right_invite_group',
            field=models.BooleanField(default=False, verbose_name='Приглашать в группу'),
        ),
    ]
